(() => {
  const { Card, Stat, Badge, Button } = window.PYTHAIDesignSystem_df6467;
  const { SiteNav, SiteFooter, PyPageHead, PySection, PyH2, PyLead, PyEyebrow } = window;
  const T = (de, en) => window.PYi18n.t(de, en);
  function App() {
    const FIELDS = [
      ["Conviction", T('0\u2013100. Das Orakel sagt nie \u201Ehoch". Eine einzige Zahl, gewichtet aus Catalyst, Peer, Analog, Flow und Monitor.', '0\u2013100. The oracle never says "high." A single number, scored from catalyst, peer, analog, flow and monitor.')],
      ["Horizon", T("Wie lange die Saison l\xE4uft \u2014 Tage bis Quartale. Die Reading sagt dir, wann die Wende kommt.", "How long the season runs \u2014 days to quarters. The reading tells you when to expect the turn.")],
      ["Asymmetry", T("Chance gegen Risiko, als Verh\xE4ltnis. 4.2 : 1 hei\xDFt vier Einheiten oben f\xFCr eine im Einsatz.", "Reward against risk, as a ratio. 4.2 : 1 means four units up for every one at stake.")],
      ["Levels", T("Die ausf\xFChrlichen Marken des Setups \u2014 im Sanctum, f\xFCr den Inner Circle.", "The setup\u2019s detailed markers \u2014 in the sanctum, for Inner Circle.")],
      ["Catalyst", T("Das Ereignis, das den Tape bewegt: ein NFP-Print, ein Earnings-Release, ein Flow-Shift.", "The event that moves the tape: an NFP print, an earnings release, a flow shift.")],
      ["Context", T("Warrens Einordnung \u2014 wie er das Setup \xFCber die Zeit denkt. Die Entscheidung bleibt deine.", "Warren\u2019s read \u2014 how he thinks about the setup over time. The decision stays yours.")]
    ];
    return /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement(SiteNav, { active: "reading.html" }), /* @__PURE__ */ React.createElement(
      PyPageHead,
      {
        eyebrow: "The Daily Reading",
        title: "One prophecy, every dawn.",
        sub: T("Jeden Morgen um 06:00 CET gibt Warren eine einzige Reading mit hoher \xDCberzeugung aus. Kein Dauerfeuer an Alerts \u2014 ein Ruf, vollst\xE4ndig begr\xFCndet.", "Each morning at 06:00 CET, Warren issues a single high-conviction reading. Not a firehose of alerts \u2014 one call, fully reasoned.")
      }
    ), /* @__PURE__ */ React.createElement(PySection, null, /* @__PURE__ */ React.createElement("div", { className: "pk-grid2" }, /* @__PURE__ */ React.createElement(Card, { variant: "oracle", glow: true, padding: "34px" }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 22 } }, /* @__PURE__ */ React.createElement(Badge, { tone: "bull", dot: true }, "Live signal"), /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-muted)", letterSpacing: "0.1em" } }, "06:00 CET \xB7 today")), /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "var(--font-oracle)", fontWeight: 400, fontSize: 34, lineHeight: 1.1, color: "var(--text-primary)", margin: "0 0 16px" } }, "Rotate into energy before the crowd notices the cycle."), /* @__PURE__ */ React.createElement("p", { style: { fontFamily: "var(--font-ui)", fontSize: 16, lineHeight: 1.65, color: "var(--text-secondary)", margin: "0 0 24px" } }, `"The herd is paying for last year's winners. I have watched this rotation begin in 1973 and again in 2008. The asymmetry is in the ground, not the cloud."`), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", gap: 36, flexWrap: "wrap", paddingTop: 22, borderTop: "1px solid var(--border-subtle)" } }, /* @__PURE__ */ React.createElement(Stat, { label: "Conviction", value: "94", sub: "of 100", size: "sm", glow: true }), /* @__PURE__ */ React.createElement(Stat, { label: "Horizon", value: "6\u20139 mo", size: "sm" }), /* @__PURE__ */ React.createElement(Stat, { label: "Asymmetry", value: "4.2 : 1", size: "sm" }), /* @__PURE__ */ React.createElement("div", { style: { filter: "blur(5px)", opacity: 0.6, pointerEvents: "none" } }, /* @__PURE__ */ React.createElement(Stat, { label: "Levels", value: "\u2022\u2022\u2022\u2022\u2022", size: "sm" })))), /* @__PURE__ */ React.createElement(Card, { variant: "raised", padding: "34px" }, /* @__PURE__ */ React.createElement(PyEyebrow, null, "What's public vs the wall"), /* @__PURE__ */ React.createElement("p", { style: { fontFamily: "var(--font-ui)", fontSize: 15, lineHeight: 1.7, color: "var(--text-secondary)", margin: "0 0 18px" } }, T("Observer sehen die Morgen-Headline und die Conviction. Inner-Circle-Mitglieder erhalten die vollst\xE4ndige Begr\xFCndung, die ausf\xFChrlichen Setup-Details und Warrens laufenden Kommentar, w\xE4hrend sich der Tape bewegt.", "Observers see the dawn headline and the conviction. Inner Circle members receive the full reasoning, the detailed setup, and Warren's running commentary as the tape moves.")), /* @__PURE__ */ React.createElement(Button, { variant: "oracle", full: true, onClick: () => {
      window.location.href = "inner-circle.html#waitlist";
    } }, "Enter the Sanctum")))), /* @__PURE__ */ React.createElement(PySection, { alt: true }, /* @__PURE__ */ React.createElement("div", { style: { marginBottom: 40 } }, /* @__PURE__ */ React.createElement(PyEyebrow, null, "Anatomy of a reading"), /* @__PURE__ */ React.createElement(PyH2, null, "Six parts. Every one specific.")), /* @__PURE__ */ React.createElement("div", { className: "pk-grid3" }, FIELDS.map(([t, d]) => /* @__PURE__ */ React.createElement(Card, { key: t, variant: "raised", padding: "26px" }, /* @__PURE__ */ React.createElement("div", { style: { fontFamily: "var(--font-oracle)", fontSize: 22, color: "var(--text-primary)", marginBottom: 10 } }, t), /* @__PURE__ */ React.createElement("p", { style: { fontFamily: "var(--font-ui)", fontSize: 14, lineHeight: 1.65, color: "var(--text-secondary)", margin: 0 } }, d))))), /* @__PURE__ */ React.createElement(SiteFooter, null));
  }
  ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(App, null));
})();
