(() => {
  const { Button, Badge, Card, Stat } = window.PYTHAIDesignSystem_df6467;
  const { SiteNav, SiteFooter, PyEyebrow } = window;
  const { useState, useEffect } = React;
  const T = (de, en) => window.PYi18n.t(de, en);
  const API = "https://api.pythai.ch";
  const TIER = { observer: "Observer", "inner-circle": "Inner Circle", syndicate: "Syndicate" };
  const PRICE = { observer: T("Kostenlos", "Free"), "inner-circle": "CHF 290 / mo", syndicate: T("Auf Einladung", "By counsel") };
  function Account() {
    const [state, setState] = useState("loading");
    const [a, setA] = useState(null);
    const justJoined = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("welcome") === "1";
    useEffect(() => {
      fetch(API + "/api/account", { credentials: "include" }).then((r) => r.ok ? r.json() : null).then((d) => {
        if (d && d.ok) {
          setA(d);
          setState("in");
        } else setState("out");
      }).catch(() => setState("out"));
    }, []);
    if (state === "loading") return /* @__PURE__ */ React.createElement("div", { style: { minHeight: "50vh", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-oracle)", fontStyle: "italic", fontSize: 22, color: "var(--text-oracle)" } }, T("Das Orakel erkennt dich\u2026", "The oracle recognises you\u2026"));
    if (state === "out") return /* @__PURE__ */ React.createElement("div", { style: { maxWidth: 460, margin: "0 auto", textAlign: "center" } }, /* @__PURE__ */ React.createElement("img", { src: "assets/logo/pythai-oculus.svg", alt: "", style: { width: 60, height: 60, margin: "0 auto 22px", opacity: 0.7 } }), /* @__PURE__ */ React.createElement("h1", { style: { fontFamily: "var(--font-oracle)", fontWeight: 400, fontSize: 40, margin: 0, color: "var(--text-primary)" } }, T("Nicht angemeldet.", "Not signed in.")), /* @__PURE__ */ React.createElement("p", { style: { fontFamily: "var(--font-ui)", fontSize: 16, color: "var(--text-secondary)", margin: "16px 0 28px", lineHeight: 1.6 } }, T("Deine Sitzung ist abgelaufen oder der Link wurde schon benutzt.", "Your session has expired or the link was already used.")), /* @__PURE__ */ React.createElement(Button, { variant: "oracle", onClick: () => {
      window.location.href = "register.html";
    } }, T("Zum Login", "Go to sign in")));
    const tier = a.tier || "observer";
    const isObserver = tier === "observer";
    function logout() {
      fetch(API + "/api/logout", { method: "POST", credentials: "include" }).finally(() => {
        window.location.href = "index.html";
      });
    }
    return /* @__PURE__ */ React.createElement("div", { style: { maxWidth: 760, margin: "0 auto" } }, justJoined && /* @__PURE__ */ React.createElement("div", { style: { border: "1px solid var(--border-oracle)", background: "rgba(212,169,78,0.07)", borderRadius: 10, padding: "16px 20px", marginBottom: 28, textAlign: "center" } }, /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-oracle)", fontStyle: "italic", fontSize: 20, color: "var(--text-oracle)" } }, T("Du bist drin. Willkommen im Sanctum.", "You\u2019re in. Welcome to the sanctum."))), /* @__PURE__ */ React.createElement("div", { style: { marginBottom: 30 } }, /* @__PURE__ */ React.createElement(PyEyebrow, null, T("Dein Account", "Your account")), /* @__PURE__ */ React.createElement("h1", { style: { fontFamily: "var(--font-oracle)", fontWeight: 400, letterSpacing: "-0.02em", fontSize: "clamp(34px,5vw,52px)", lineHeight: 1.05, margin: 0, color: "var(--text-primary)" } }, a.name ? a.name : T("Member", "Member")), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 12, marginTop: 14, flexWrap: "wrap" } }, /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-mono)", fontSize: 13, color: "var(--text-secondary)" } }, a.email), a.status && /* @__PURE__ */ React.createElement(Badge, { tone: "neutral", variant: "outline" }, a.status))), /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 }, className: "acc-grid" }, /* @__PURE__ */ React.createElement(Card, { variant: "oracle", glow: true, padding: "28px" }, /* @__PURE__ */ React.createElement(PyEyebrow, null, T("Deine Subscription", "Your subscription")), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", alignItems: "baseline", gap: 10, margin: "8px 0 4px" } }, /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-oracle)", fontSize: 30, color: "var(--text-primary)" } }, TIER[tier]), /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-mono)", fontSize: 14, color: "var(--text-muted)" } }, PRICE[tier])), a.memberSince && /* @__PURE__ */ React.createElement("div", { style: { fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-muted)" } }, T("Mitglied seit", "Member since"), " ", a.memberSince), /* @__PURE__ */ React.createElement("div", { style: { marginTop: 20 } }, isObserver ? /* @__PURE__ */ React.createElement(Button, { variant: "oracle", full: true, onClick: () => {
      window.location.href = "inner-circle.html#waitlist";
    } }, T("Upgrade auf Inner Circle", "Upgrade to Inner Circle")) : /* @__PURE__ */ React.createElement(Button, { variant: "chrome", full: true, onClick: () => {
      window.location.href = "inner-circle.html";
    } }, T("Subscription verwalten", "Manage subscription")))), /* @__PURE__ */ React.createElement(Card, { variant: "raised", padding: "28px" }, /* @__PURE__ */ React.createElement(PyEyebrow, null, T("Zugang", "Access")), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 12, marginTop: 10 } }, [
      [T("Morgen-Headline", "Dawn headline"), true],
      [T("Conviction-Score", "Conviction score"), true],
      [T("Volle Reading + Levels", "Full reading + levels"), !isObserver],
      [T("Live-Signale", "Live signals"), !isObserver],
      [T("Warren im Gespr\xE4ch", "Warren in conversation"), !isObserver]
    ].map(([label, on]) => /* @__PURE__ */ React.createElement("div", { key: label, style: { display: "flex", alignItems: "center", gap: 10, fontFamily: "var(--font-ui)", fontSize: 14, color: on ? "var(--text-secondary)" : "var(--text-muted)" } }, /* @__PURE__ */ React.createElement("span", { style: { color: on ? "var(--oracle)" : "var(--iron)" } }, on ? "\u2713" : "\u25CB"), label))))), /* @__PURE__ */ React.createElement(Card, { variant: "raised", padding: "30px", style: { marginBottom: 30 } }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, flexWrap: "wrap", gap: 10 } }, /* @__PURE__ */ React.createElement(PyEyebrow, null, T("Die heutige Reading", "Today\u2019s reading")), /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-muted)" } }, "06:00 CET")), /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "var(--font-oracle)", fontWeight: 400, fontSize: 28, lineHeight: 1.15, color: "var(--text-primary)", margin: "0 0 16px" } }, "Rotate into energy before the crowd notices the cycle."), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", gap: 30, flexWrap: "wrap", paddingTop: 16, borderTop: "1px solid var(--border-subtle)" } }, /* @__PURE__ */ React.createElement(Stat, { label: "Conviction", value: "94", sub: "of 100", size: "sm" }), isObserver ? /* @__PURE__ */ React.createElement("div", { style: { filter: "blur(5px)", opacity: 0.6, pointerEvents: "none" } }, /* @__PURE__ */ React.createElement(Stat, { label: "Entry / Stop / Target", value: "\u2022\u2022\u2022\u2022\u2022", size: "sm" })) : /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Stat, { label: "Entry", value: "123.32", size: "sm" }), /* @__PURE__ */ React.createElement(Stat, { label: "Stop", value: "119.50", size: "sm" }), /* @__PURE__ */ React.createElement(Stat, { label: "Target", value: "127.00", size: "sm" }))), isObserver && /* @__PURE__ */ React.createElement("p", { style: { fontFamily: "var(--font-ui)", fontSize: 13, color: "var(--text-muted)", margin: "16px 0 0" } }, T("Levels und das volle Reasoning sind dem Inner Circle vorbehalten.", "Levels and the full reasoning are reserved for the Inner Circle.")), /* @__PURE__ */ React.createElement("p", { style: { fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--text-muted)", margin: "14px 0 0" } }, T("Beispiel-Reading. Live-Inhalte kommen von Warren, server-seitig pro Tier.", "Sample reading. Live content comes from Warren, served per tier."))), /* @__PURE__ */ React.createElement("div", { style: { textAlign: "center" } }, /* @__PURE__ */ React.createElement(Button, { variant: "ghost", onClick: logout }, T("Abmelden", "Log out"))));
  }
  function App() {
    return /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement(SiteNav, { active: "" }), /* @__PURE__ */ React.createElement("section", { style: { position: "relative", minHeight: "calc(100vh - var(--nav-h))", padding: "64px 24px", overflow: "hidden" } }, /* @__PURE__ */ React.createElement("div", { style: { position: "absolute", inset: 0, pointerEvents: "none", background: "radial-gradient(70% 50% at 50% 0%, var(--glow-oracle-soft) 0%, transparent 60%)" } }), /* @__PURE__ */ React.createElement("div", { style: { position: "relative" } }, /* @__PURE__ */ React.createElement(Account, null))), /* @__PURE__ */ React.createElement(SiteFooter, null));
  }
  ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(App, null));
})();
