(() => {
  const { SiteNav, SiteFooter, PyPageHead, PySection, PyEyebrow } = window;
  const { useEffect } = React;
  const T = (de, en) => window.PYi18n.t(de, en);
  function App() {
    useEffect(() => {
      var id = (window.location.hash || "").slice(1);
      if (!id) return;
      setTimeout(function () {
        var el = document.getElementById(id);
        if (!el) return;
        var top = el.getBoundingClientRect().top + window.scrollY - 90;
        window.scrollTo({ top: top, behavior: "smooth" });
      }, 60);
    }, []);
    const SECTIONS = [
      ["imprint", T("Impressum", "Imprint"), [
        T("PYTHAI UG (haftungsbeschr\xE4nkt) i.G.", "PYTHAI UG (haftungsbeschr\xE4nkt) i.G. \u2014 UG in formation."),
        { muted: true, text: T("ein Startup der CRAiD GmbH", "a startup of CRAiD GmbH") },
        T("Anschrift: Kollwitzstr. 60, 10435 Berlin, Germany.", "Address: Kollwitzstr. 60, 10435 Berlin, Germany."),
        T("Vertretungsberechtigt: Daniel Simon.", "Authorised representative: Daniel Simon."),
        T("Kontakt: hello@pythai.ch.", "Contact: hello@pythai.ch."),
        T("Handelsregister / Registergericht: [in progress]. USt-IdNr.: [in progress].", "Commercial register / court: [in progress]. VAT ID: [in progress].")
      ]],
      ["privacy", T("Datenschutz", "Privacy"), [
        T("Verantwortliche Stelle: PYTHAI UG (haftungsbeschr\xE4nkt) i.G. Datenschutz-Kontakt: privacy@pythai.ch.", "Controller: PYTHAI UG (haftungsbeschr\xE4nkt) i.G. Privacy contact: privacy@pythai.ch."),
        T("Waitlist & Newsletter: Wir verarbeiten deine E-Mail-Adresse auf Grundlage deiner Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Die Anmeldung erfolgt im Double-Opt-in \u2014 erst nach Klick auf den Best\xE4tigungslink wirst du kontaktiert. Den Zeitpunkt der Einwilligung speichern wir als Nachweis. Du kannst jederzeit \xFCber den Abmeldelink in jeder E-Mail oder per Mail an warren@pythai.ch widerrufen.", "Waitlist & newsletter: we process your email address on the basis of your consent (Art. 6(1)(a) GDPR). Sign-up uses double opt-in \u2014 you are only contacted after clicking the confirmation link. We store the time of consent as proof. You may withdraw anytime via the unsubscribe link in any email or by mailing warren@pythai.ch."),
        T("Konto & Login: F\xFCr Anmeldung und Login verarbeiten wir E-Mail-Adresse und Anmeldedaten zur Bereitstellung des Mitgliederbereichs (Vertragserf\xFCllung / berechtigtes Interesse). Der Login ist passwortlos \xFCber einen einmaligen Magic-Link.", "Account & login: for sign-up and login we process your email and session data to provide the member area (contract / legitimate interest). Login is passwordless via a one-time magic link."),
        T("SMS-Benachrichtigungen & Mobilnummer: Aktivierst du SMS-Alerts, verarbeiten wir deine Mobilnummer auf Grundlage deiner Einwilligung (Art. 6 Abs. 1 lit. a DSGVO), einschlie\xDFlich einer Verifizierung per Einmal-Code. Du kannst SMS-Alerts jederzeit deaktivieren und den Widerruf damit aus\xFCben. Der SMS-Versand erfolgt \xFCber einen spezialisierten Versanddienstleister als Auftragsverarbeiter.", "SMS notifications & mobile number: if you enable SMS alerts, we process your mobile number on the basis of your consent (Art. 6(1)(a) GDPR), including a one-time-code verification. You may disable SMS alerts at any time, thereby withdrawing consent. SMS delivery is handled by a specialised messaging provider acting as processor."),
        T("My Book (Syndicate): F\xFCr dein pers\xF6nliches Thesen-Buch speichern wir die von dir eingegebenen Inhalte (Instrument, ISIN, deine These und Anti-These sowie die von dir gesetzten Kurs-Marken) zur Bereitstellung der Funktion (Vertragserf\xFCllung). Zur Marken-Auslesung hochgeladene Screenshots oder PDFs werden nicht gespeichert — nur die daraus ausgelesenen Werte; die Bildauswertung erfolgt durch einen KI-Auftragsverarbeiter.", "My Book (Syndicate): for your personal thesis book we store the content you enter (instrument, ISIN, your thesis and anti-thesis, and the price levels you set) to provide the feature (contract). Screenshots or PDFs uploaded for level extraction are not stored — only the extracted values; image analysis is performed by an AI processor."),
        T("Auftragsverarbeiter: Resend (E-Mail-Versand), Notion (Kontakt-/Member-Verwaltung), Vercel (Website-Hosting & Reichweitenmessung), Anthropic (Warren-Chat), Google (Gemini — Bild-/Marken-Auslesung im Feature „My Book“) sowie ein SMS-Versanddienstleister (SMS-Alerts). Mit allen bestehen bzw. werden Auftragsverarbeitungsvertr\xE4ge geschlossen.", "Processors: Resend (email delivery), Notion (contact/member management), Vercel (website hosting & analytics), Anthropic (Warren chat), Google (Gemini — image/level extraction in the “My Book” feature) and an SMS messaging provider (SMS alerts). Data-processing agreements are in place or being concluded with each."),
        T("Cookies & lokale Speicherung: Diese Website setzt keine Tracking-, Werbe- oder Analyse-Cookies und zeigt deshalb keinen Cookie-Banner. Technisch notwendig ist allein ein Login-Cookie (pythai_session, HttpOnly, 30 Tage), das erst nach deiner Anmeldung gesetzt wird (\xA7 25 Abs. 2 TDDDG). Zus\xE4tzlich speichern wir zwei rein funktionale Einstellungen lokal in deinem Browser — Sprache und Ton an/aus — ohne personenbezogene Daten und nur, wenn du sie selbst ausl\xF6st.", "Cookies & local storage: this website sets no tracking, advertising or analytics cookies and therefore shows no cookie banner. The only strictly necessary cookie is a login cookie (pythai_session, HttpOnly, 30 days), set only after you sign in (\xA7 25(2) TDDDG). We also store two purely functional settings locally in your browser — language and sound on/off — with no personal data, and only when you trigger them yourself."),
        T("Reichweitenmessung: Zur anonymen Reichweitenmessung nutzen wir Vercel Web Analytics. Der Dienst arbeitet cookielos, speichert nichts auf deinem Endger\xE4t und bildet keine personenbezogenen Profile; Anfragen werden zu einem t\xE4glich wechselnden Hash-Wert verarbeitet. Rechtsgrundlage ist unser berechtigtes Interesse an einer datensparsamen Statistik (Art. 6 Abs. 1 lit. f DSGVO).", "Audience measurement: for anonymous audience measurement we use Vercel Web Analytics. The service is cookieless, stores nothing on your device and builds no personal profiles; requests are processed into a daily-rotating hash. The legal basis is our legitimate interest in privacy-friendly statistics (Art. 6(1)(f) GDPR)."),
        T("Schriftarten: Alle Webfonts werden selbst von unserem Server (pythai.ch) ausgeliefert. Es werden keine Schriften von Google Fonts oder anderen Drittanbietern geladen — deine IP-Adresse wird dabei nicht an Dritte \xFCbertragen.", "Fonts: all webfonts are served from our own server (pythai.ch). No fonts are loaded from Google Fonts or other third parties — your IP address is not transmitted to any third party."),
        T("Deine Rechte: Auskunft, Berichtigung, L\xF6schung, Einschr\xE4nkung, Daten\xFCbertragbarkeit, Widerspruch sowie Widerruf erteilter Einwilligungen. Wende dich an privacy@pythai.ch. Speicherdauer, vollst\xE4ndige Rechtsgrundlagen und Beschwerderecht bei der Aufsichtsbeh\xF6rde werden vor dem Live-Gang erg\xE4nzt.", "Your rights: access, rectification, erasure, restriction, portability, objection and withdrawal of consent. Contact warren@pythai.ch. Retention periods, full legal bases and the right to lodge a complaint with the supervisory authority will be added before launch.")
      ]],
      ["terms", T("AGB", "Terms"), [
        T("Entwurf — Struktur zur anwaltlichen Ausformulierung. Anbieter: PYTHAI UG (haftungsbeschr\xE4nkt) i.G.", "Draft — structure for legal finalisation. Provider: PYTHAI UG (haftungsbeschr\xE4nkt) i.G."),
        T("0 · Beta-Phase / Testbetrieb. PYTHAI befindet sich in einer offenen Beta- bzw. Testphase und ist ausdr\xFCcklich nicht stabil. Funktionen, Inhalte, Daten und Verf\xFCgbarkeit k\xF6nnen sich jederzeit \xE4ndern, unvollst\xE4ndig oder fehlerhaft sein, ausfallen oder ohne Vorank\xFCndigung eingestellt werden. Die Bereitstellung erfolgt „wie besehen“ und ohne Gew\xE4hr. Aus der Nutzung w\xE4hrend der Beta-Phase lassen sich — soweit gesetzlich zul\xE4ssig — keine Rechtsanspr\xFCche herleiten, insbesondere nicht auf Verf\xFCgbarkeit, Fehlerfreiheit, bestimmte Funktionen, Datenerhalt oder wirtschaftliche Ergebnisse. Zwingende gesetzliche Verbraucherrechte sowie die Haftung nach Ziffer 9 bleiben unber\xFChrt.", "0 · Beta phase / test operation. PYTHAI is in an open beta or test phase and is expressly not stable. Features, content, data and availability may change at any time, be incomplete or faulty, fail, or be discontinued without notice. The service is provided “as is” and without warranty. To the extent permitted by law, no legal claims can be derived from use during the beta phase — in particular none to availability, freedom from errors, specific features, data retention or economic outcomes. Mandatory statutory consumer rights and liability under clause 9 remain unaffected."),
        T("1 · Geltungsbereich. Diese AGB gelten f\xFCr alle PYTHAI-Subscriptions (Observer / Inner Circle / Syndicate).", "1 · Scope. These terms apply to all PYTHAI subscriptions (Observer / Inner Circle / Syndicate)."),
        T("2 · Leistung & Charakter. PYTHAI ist ein Publisher (Finanzpublikation), Warren ein KI-Kolumnist. Die Inhalte sind redaktionelle Markt-Einsch\xE4tzungen zur Information und Inspiration — keine Anlageberatung, keine Anlagevermittlung, keine individuelle Empfehlung.", "2 · Service & character. PYTHAI is a publisher (financial publication); Warren is an AI columnist. The content is editorial market commentary for information and inspiration — not investment advice, broking or individual recommendation."),
        T("2a · Abgrenzung der Leistung. PYTHAI ist insbesondere keine Trading-Plattform, kein Broker, keine Verwahrstelle und kein Verm\xF6gensverwalter. Wir f\xFChren keine Order aus, halten weder Gelder noch Wertpapiere, verwalten keine Portfolios und bieten kein Copy- oder Social-Trading. Der Handel erfolgt ausschlie\xDFlich \xFCber deinen eigenen Broker; alle Entscheidungen triffst du eigenverantwortlich. „My Book“ ist ein rein kursbasiertes Thesen-Notizbuch ohne Order-, Depot- oder Gewinn-/Verlust-Funktion.", "2a · Service boundaries. In particular, PYTHAI is not a trading platform, broker, custodian or asset manager. We execute no orders, hold neither funds nor securities, manage no portfolios and offer no copy or social trading. Trading happens solely through your own broker; you make all decisions on your own responsibility. “My Book” is a purely price-based thesis notebook with no order, custody or profit/loss function."),
        T("3 · Zugang & Freigabe. Die Mitgliedschaft setzt die Best\xE4tigung der erforderlichen Einwilligungen (AGB, Risikohinweis, KI-Hinweis, Eigenverantwortung) sowie eine Freigabe durch PYTHAI voraus. Es besteht kein Anspruch auf Aufnahme.", "3 · Access & approval. Membership requires confirming the necessary consents (terms, risk notice, AI notice, own responsibility) and approval by PYTHAI. There is no entitlement to admission."),
        T("4 · Vertragsschluss & Laufzeit. Bezahlte Subscriptions laufen monatlich und verl\xE4ngern sich automatisch; K\xFCndigung jederzeit zum Periodenende.", "4 · Formation & term. Paid subscriptions run monthly and renew automatically; cancellable anytime to the end of the period."),
        T("5 · Preise & Zahlung. Inner Circle 69 €/Monat; Syndicate 289 €/Monat (in Vorbereitung). Vertragspartner und abrechnende Stelle f\xFCr kostenpflichtige Subscriptions ist in der aktuellen Phase die CRAiD GmbH; die Zahlungsabwicklung erfolgt \xFCber Stripe. Preise inkl. gesetzlicher USt.", "5 · Prices & payment. Inner Circle €69/month; Syndicate €289/month (in preparation). The contracting and billing entity for paid subscriptions is currently CRAiD GmbH; payments are processed via Stripe. Prices include statutory VAT."),
        T("6 · Widerruf (Fernabsatz). Verbraucher haben ein 14-t\xE4giges Widerrufsrecht. Bei sofortiger Bereitstellung digitaler Inhalte erlischt es mit ausdr\xFCcklicher Zustimmung und Kenntnisnahme des Erl\xF6schens.", "6 · Withdrawal (distance selling). Consumers have a 14-day right of withdrawal. For immediately provided digital content it lapses upon express consent and acknowledgement of the lapse."),
        T("7 · Pflichten der Nutzer. Anlageentscheidungen erfolgen eigenverantwortlich. Keine Weitergabe oder \xF6ffentliche Wiedergabe der Inhalte, keine missbr\xE4uchliche Nutzung.", "7 · User obligations. Investment decisions are made on the user’s own responsibility. No redistribution or public reproduction of the content, no abusive use."),
        T("8 · KI-Hinweis. Die Inhalte werden von einer KI (Warren) erstellt und k\xF6nnen fehlerhaft sein. Angaben ohne Gew\xE4hr.", "8 · AI notice. The content is produced by an AI (Warren) and may contain errors. No warranty is given."),
        T("9 · Haftung. Haftung nur bei Vorsatz und grober Fahrl\xE4ssigkeit sowie bei Verletzung von Leben, K\xF6rper oder Gesundheit; im \xDCbrigen beschr\xE4nkt. Keine Haftung f\xFCr Anlageergebnisse.", "9 · Liability. Liability only for intent and gross negligence and for injury to life, body or health; otherwise limited. No liability for investment outcomes."),
        T("10 · \xC4nderungen & Schlussbestimmungen. \xC4nderungen dieser AGB werden angek\xFCndigt; erneute Zustimmung bzw. fortgesetzte Nutzung gilt als Annahme. Anwendbares Recht, Gerichtsstand und salvatorische Klausel sind anwaltlich zu finalisieren.", "10 · Changes & final provisions. Changes to these terms will be announced; renewed consent or continued use constitutes acceptance. Governing law, jurisdiction and severability are to be finalised by counsel.")
      ]],
      ["risk", T("Risikohinweis", "Risk notice"), [
        T("PYTHAI befindet sich in einer Beta-/Testphase und ist nicht stabil. Inhalte, Daten und Funktionen k\xF6nnen jederzeit fehlerhaft, unvollst\xE4ndig oder nicht verf\xFCgbar sein. Die Nutzung erfolgt ohne Gew\xE4hr und auf eigenes Risiko; aus der Beta-Nutzung k\xF6nnen — soweit gesetzlich zul\xE4ssig — keine Rechtsanspr\xFCche geltend gemacht werden.", "PYTHAI is in a beta/test phase and is not stable. Content, data and features may be faulty, incomplete or unavailable at any time. Use is without warranty and at your own risk; to the extent permitted by law, no legal claims can be derived from beta use."),
        T("Warren ist eine KI und kann irren. Die Inhalte sind reine Inspiration und redaktionelle Markt-Einsch\xE4tzung — keine Garantie, kein Rat. Du triffst alle Entscheidungen eigenverantwortlich.", "Warren is an AI and can err. The content is pure inspiration and editorial market commentary — no guarantee, no advice. You make all decisions on your own responsibility."),
        T("PYTHAI / Warren stellt keine Anlageberatung, keine Anlagevermittlung, keine Finanzanalyse und keine Kauf-, Verkaufs- oder Halteempfehlung dar. Eine individuelle Eignung wird nicht gepr\xFCft.", "PYTHAI / Warren does not constitute investment advice, investment broking, financial analysis or any buy, sell or hold recommendation. Individual suitability is not assessed."),
        T("PYTHAI ist keine Trading-Plattform, kein Broker und keine Verwahrstelle: Es werden keine Orders ausgef\xFChrt und weder Gelder noch Wertpapiere verwahrt. Der Handel erfolgt \xFCber deinen eigenen Broker. Angezeigte Kurse, Setup-Niveaus und Status sind unverbindliche Momentaufnahmen und k\xF6nnen verz\xF6gert, fehlerhaft oder \xFCberholt sein.", "PYTHAI is not a trading platform, broker or custodian: no orders are executed and neither funds nor securities are held. Trading happens through your own broker. Displayed prices, setup levels and status are non-binding snapshots and may be delayed, erroneous or out of date."),
        T("Triff keine Anlageentscheidung allein auf Basis dieser Inhalte; ziehe vor jeder Entscheidung eine eigene Pr\xFCfung sowie eine lizenzierte, unabh\xE4ngige Beratung heran.", "Do not make any investment decision based solely on this content; before any decision, conduct your own review and consult licensed, independent advice."),
        T("Die PYTHAI UG (haftungsbeschr\xE4nkt) i.G. \xFCbernimmt keine Haftung f\xFCr Sch\xE4den, die aus der Nutzung dieser Informationen entstehen. Angaben ohne Gew\xE4hr. M\xE4rkte bergen Risiken.", "PYTHAI UG (haftungsbeschr\xE4nkt) i.G. accepts no liability for damages arising from the use of this information. No warranty is given. Markets carry risk.")
      ]]
    ];
    return /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement(SiteNav, { active: "legal.html" }), /* @__PURE__ */ React.createElement(PyPageHead, { eyebrow: "Legal", title: "Imprint & legal." }), SECTIONS.map(([id, title, body]) => /* @__PURE__ */ React.createElement(PySection, { key: id, alt: id === "privacy" || id === "risk" }, /* @__PURE__ */ React.createElement("div", { id, style: { maxWidth: 820 } }, /* @__PURE__ */ React.createElement("h2", { style: { fontFamily: "var(--font-oracle)", fontWeight: 400, fontSize: 32, color: "var(--text-primary)", margin: "0 0 18px" } }, title), body.map((p, i) => p && typeof p === "object" && p.muted ? /* @__PURE__ */ React.createElement("p", { key: i, style: { fontFamily: "var(--font-ui)", fontSize: 12.5, lineHeight: 1.5, color: "var(--text-muted)", margin: "-8px 0 16px" } }, p.text) : /* @__PURE__ */ React.createElement("p", { key: i, style: { fontFamily: "var(--font-ui)", fontSize: 15, lineHeight: 1.7, color: "var(--text-secondary)", margin: "0 0 14px", maxWidth: "80ch" } }, p))))), /* @__PURE__ */ React.createElement(SiteFooter, null));
  }
  ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(App, null));
})();
